---

- block:
  - name: set fact for Mutable Instruments ugen installs
    set_fact:
      sc_mutable_installed: True
      sc_synthdefs_installed: True

  - name: create ugens dest directories
    file:
      path: "{{ sc_ext_dir }}"
      state: directory
      mode: 0775
      recurse: yes

  - file:
      path: "{{ sc_conf_dir }}/{{ sc_synthdef_dir }}"
      state: directory
      mode: 0775
      recurse: yes

  - name: download/extract mutable instruments ugens bundle
    unarchive:
      src: "{{ miugen_package_src }}"
      dest: "{{ sc_ext_dir }}"
      remote_src: True

  - name: create synth_def dir (if required)
    file:
      path: "{{ sc_conf_dir }}/{{ sc_synthdef_dir }}"
      state: directory
      mode: '0775'

  - name: copy mutable instruments ugens synth defs
    get_url:
      url: "{{ miugen_synthdef_src }}"
      dest: "{{ sc_conf_dir }}/{{ sc_synthdef_dir }}/mutable-instruments.scd"
      mode: 0640

  - name: create required config scripts directory
    file:
      path: "/home/{{ansible_env.SUDO_USER}}/.local/share/ansible-tidalcycles/scripts/"
      state: directory
      recurse: yes

  - name: copy mutable-instruments params file to scripts dir
    get_url:
      url: "{{ miugen_params_src }}"
      dest: "/home/{{ansible_env.SUDO_USER}}/.local/share/ansible-tidalcycles/scripts/mutable-instruments-ugens_parameters.hs"
      mode: 0640

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'
